// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhaypbkhuljrdmpqzgms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoYXlwYmtodWxqcmRtcHF6Z21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjg2MDgsImV4cCI6MjA2NDg0NDYwOH0.5QvbvaR5tNhNQ_vPYyJXnGA2ajpKmLbSUGNJN1vsG5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);