// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvwfwllqnawavzggpuje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2d2Z3bGxxbmF3YXZ6Z2dwdWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDkwNTQsImV4cCI6MjA2NDU4NTA1NH0.eHw-IcRBcnUY_CInQlb8hgZMO7807y0q9jLZTrFOUQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);